### ISSUE TITLE
Platformio library version bump

### ISSUE THREAD

**Issue by chacal** [finitespace/BME280#10]
Hi!

Would it be possible to bump up the version string in `library.properties` to 2.0.0 to match the latest release?

It seems that the version Platformio currently distributes is somehow broken as I get the following compile error:

> BME280I2C.h:56:23: error: expected ')' before 'tosr'

By looking at the commits in this repository, it seems that the bug has already been fixed, but the updated version is not available from platformio. This might get resolved if the library version would be updated.

**Comment by chacal** [comment]
Just FYI.. By cloning the latest version of the repository the compile error disappears. So we'd just need platformio to provide the latest version as well.

**Comment by finitespace** [comment]
Done. Give it a roll now.

**Comment by chacal** [comment]
Just tested it and works perfectly. Thanks! :)
