### ISSUE TITLE
Sw I2C for BME280

### ISSUE THREAD

**Issue by cmoine** [finitespace/BME280#100]
Is there any particular reason I can't find a BME280 driver that use software i2c ?

You'll probably tell me: why don't you use SPI ? Because I have 3 sensors that only accepts i2c :( :(

Why software i2c ? Because my Arduino is already a I2C slave of a Raspberry :)

I already worked on adapting a BME280 library so use software I2C, but unfortunately, the version doesn't compile with newer version (that is the problem when we "fork" a project).

Would you eventually be interested in a Pull Request for this ?

**Comment by cmoine** [comment]
Ups, I guess need to combine this library with Brzo ? :)

**Comment by idesignstuff** [comment]
I've only ever used this lib with I2C, for years.
It's running with 3v3,Gnd,SCL,SDA wires on several Wemos D1 minis, flashed
with either platformio in Atom, or Arduino IDE.
I've had 2 BME's wired to the same SDA and SCL pins, with two different I2C
addresses, and it worked flawlessly.

Christian

**Comment by cmoine** [comment]
Problem with Brzo:
WARNING: library Brzo_I2C claims to run on (esp8266) architecture(s) and may be incompatible with your current board which runs on (avr) architecture(s).
And it doesn't even build :-(

**Comment by idesignstuff** [comment]
No need for BRZO. I2C is built into BME280 by FiniteSpace.

Christian

**Comment by idesignstuff** [comment]
https://github.com/finitespace/BME280#settings
Christian

**Comment by cmoine** [comment]
Thank you Christian, but I2C for Arduino Nano is bounded to A4 & A5.

How do I use D2 & D3 for instance ?

Only solution remaining I guess is using this:
https://github.com/felias-fogg/SoftI2CMaster

**Comment by finitespace** [comment]
Yeah, Brzo needs to be discontinued. Unless you are running an esp, you shouldn’t need it.

**Comment by finitespace** [comment]
Thank you everyone for responding to this. I know I have been amiss in my duties this year. Hopefully, I will have some time over Xmas break to contribute to changes.

I value the support group this library has gained.

Regards,
Finitespace or should I say, finitespacetime ;)

**Comment by finitespace** [comment]
Implement your solution. I will take a look.

**Comment by cmoine** [comment]
But wait a minute, I looked at Git  branches, and one is named softwarewire, which make use of SoftwareWire.h... A library for software I2C on any pin: this is exactly what I need ? Is this working ? Any plan to integrate it in the main branch ?

**Comment by cmoine** [comment]
It works ! however, I encounter a GCC segmentation fault when I comment one of these lines
```
 bme.read(pres, temp, hum, tempUnit, presUnit);
  ...
  Wire.write("{\"temperature\":");
```
GCC seg fault with arduino are very anoying :( :( Any tip ?

**Comment by cmoine** [comment]
Ok found the issue GCC:
http://forum.arduino.cc/index.php?topic=583509

**Comment by cmoine** [comment]
Ok it seems to work, but still some problem to fix on my side, and it seems that I have burnt my Arduino somehow, so my tests will ahve to wait next Arduino order :) Is it possible to merge/publish this ?
