### ISSUE TITLE
BME280 no humidity :(

### ISSUE THREAD

**Issue by dmagyar** [finitespace/BME280#125]
First off, did you read the manual? Did it answer your question? 
Second, did you look at the examples? Did they answer your question? 
No, alright, please discribe the problem below.

### Expected behavior

Humidity shows something other than 0.0000%

### Actual behavior

Humidity shows as 0.0000%

### Steps to reporduce the behavior

Wire up and run the example. I have tried many BME modules, granted from the same supplier.

```
Found BME280 sensor! Success.

Temp: 23.16°C           Humidity: 0.00% RH              Pressure: 16755628.00Pa

Temp: 23.89°C           Humidity: 0.00% RH              Pressure: 16755609.00Pa

Temp: 23.87°C           Humidity: 0.00% RH              Pressure: 16755609.00Pa

Temp: 23.84°C           Humidity: 0.00% RH              Pressure: 16755610.00Pa

Temp: 23.80°C           Humidity: 0.00% RH              Pressure: 16755611.00Pa

```

According to the chip_id it is a BME280, although it has no metal casing on it.

**Comment by finitespace** [comment]
send the chips back, they are bmp chips
