### ISSUE TITLE
Version 2.1.0

### ISSUE THREAD

**Issue by W4KRL** [finitespace/BME280#17]
Version 1.0.0 works fine but the IDE keeps nagging me to update to the latest 2.1.0 version. This is what happens with 2.1.0:

Arduino: 1.6.13 (Windows 10), Board: "WeMos D1 R2 & mini, 80 MHz, 115200, 4M (3M SPIFFS)"

Build options changed, rebuilding all
C:\Users\Karl\OneDrive\Arduino\libraries\BME280\src\BME280SpiSw.cpp:36:29: fatal error: Adafruit_BMP280.h: No such file or directory

 #include <Adafruit_BMP280.h>

                             ^

compilation terminated.

exit status 1
Error compiling for board WeMos D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by osos** [comment]
I have seen the same with platformio.

Workaround, delete the SPI related files and use the i2c

**Comment by finitespace** [comment]
This issue has already been fixed in V2.1.01. #13 

Tyler

**Comment by osos** [comment]
@finitespace, unfortunately it seems not to resolved with the version Platformio library collects:

`Compiling .pioenvs/d1_mini/lib/BME280_ID901/BME280Spi.o`
`Compiling .pioenvs/d1_mini/lib/BME280_ID901/BME280SpiSw.o`
`/home/johannes/.platformio/lib/BME280_ID901/src/BME280Spi.cpp:34:17: fatal error: SPI.h: No such file or directory`
`#include <SPI.h>`
`^`
`compilation terminated.`

I do not get why SPI is compiled when I only use i2c!

**Comment by MacNetron** [comment]
I've got the same issue on v2.1.0, linux mint 18, Arduino 1.8.0:

`Arduino: 1.8.0 (Linux), Board: "Arduino Nano, ATmega328"

/home/mjfdreus/Arduino/libraries/BME280/src/BME280SpiSw.cpp:36:29: fatal error: Adafruit_BMP280.h: No such file or directory
 #include <Adafruit_BMP280.h>
                             ^
compilation terminated.
exit status 1
Error compiling for board Arduino Nano.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

The Arduino IDE does not have this library with a version higher than version 2.1.0  in the Manage Libraries Window.

BTW, as indicated above, v1.0.0 does work correctly on I2C.

**Comment by coelner** [comment]
@MacNetron You need to download the latest version from here: https://github.com/finitespace/BME280/releases/tag/Release_Version_2.1.01
Arduino keeps moaning, that the version is unknown. To solve that issue, you need to change the version string in the library.properties back to 2.1.0

**Comment by finitespace** [comment]
I just added a tag for Release 2.1.2. It might take a little for it to be incorporated into the Arduino libraries. But let me know if you can see it after about 24 hours.

Tyler

**Comment by coelner** [comment]
Works for me.

**Comment by MCeddy** [comment]
I have the same error like @psi-4ward 
After adding #include <SPI.h> it works on ESP32 :)

**Comment by psi-4ward** [comment]
Issue still exists :\

**Comment by teemuniiranen** [comment]
Yep, still existing with PlatformIO and Wemos D1 mini.

**Comment by atar-axis** [comment]
Still an issue, unfortunately.
At least on the latest PlatformIO and 3.0.0

**Comment by MichaelRChristensen** [comment]
> Still an issue, unfortunately.
> At least on the latest PlatformIO and 3.0.0

Just add.
#include <SPI.h>
in your main.cpp

Works on ESP8266 and Wemos D1 mini
