### ISSUE TITLE
Doesn´t show humidity

### ISSUE THREAD

**Issue by jkores** [finitespace/BME280#21]
I use this library with Arduino nano, it works fine except humidity - it shows all time 0,00%. Is problem on my module?
Thanks.

**Comment by idesignstuff** [comment]
I'm guessing it's either the sensor module or (more likely) your code.
I know my code is the problem most of the time.

Christian

**Comment by jkores** [comment]
Hi, thanks for fast reply.
So I thing, that it is not i my code, bacause I use included example ;) This library works for me, other libraries doesnt find my module, neither I change I2C adress.

**Comment by idesignstuff** [comment]
If you get any data from any sensor on i2c, like temp and pressure, it's
probably not the nano. Do you have another bme280 to test?

Christian

**Comment by theopensourcerer** [comment]
I've been using this library on an ESP8266 with a BME280 connected over I2C and it works fine :-)

**Comment by idesignstuff** [comment]
me too.

Actually, I have two BME's on the same i2c line, reporting their data every
30 seconds via Wemos D1 mini (esp8266).
http://184.106.153.149/channels/214155


Christian

**Comment by theopensourcerer** [comment]
Sorry, here's my project and code if it might be of help: 

https://github.com/theopensourcerer/esp8266_envmonitor

**Comment by jkores** [comment]
OK,
so I will try to buy new one - i looks, that problem is there.
Thanks to all.

**Comment by finitespace** [comment]
Jkores,

This sounds to me like you are using a BMP with the BME library, which will work fine, but you will not get humidity. BMP280 is Bosch's Pressure sensor for temperature and pressure.. BME280 is Bosch's environmental sensor for temperature, pressure, and humidity.

Tyler

**Comment by idesignstuff** [comment]
or a BME component?

Christian

**Comment by finitespace** [comment]
What do you mean Christian?

Tyler

**Comment by idesignstuff** [comment]
Sorry Tyler, I meant that he may have a BMP component wired up. That would
explain getting good data for temp and pressure, but no humidity.



Christian

**Comment by jkores** [comment]
Hi finitespace, you are right ;)
An one letter and what problems it will makes ;)
Thanks and sorry for stupid problem.

**Comment by riker65** [comment]
Hi
I assume the BME280 - which is similar to gy-b11I assume -  does provide temp, hum and pressure.

so I do not understand why humidity is not available. Have the same problem.

any solution? 

Thanks

**Comment by finitespace** [comment]
Riker65, 

Please read the earlier comments. This is because you have a BMP often packaged as a BME. Which does not show humidity. There is a print statement in the examples that will print which chip model you have.

```
 switch(bme.chipModel())
  {
     case BME280::ChipModel_BME280:
       Serial.println("Found BME280 sensor! Success.");
       break;
     case BME280::ChipModel_BMP280:
       Serial.println("Found BMP280 sensor! No Humidity available.");
       break;
     default:
       Serial.println("Found UNKNOWN sensor! Error!");
}```
