### ISSUE TITLE
'NAN' error running in Energia

### ISSUE THREAD

**Issue by denzelwamburu** [finitespace/BME280#24]
Am trying to run the program in energia and am getting the following error. 
`BME_280_I2C_Test:78: error: 'NAN' was not declared in this scope`
`exit status 1`
`'NAN' was not declared in this scope.`

**Comment by denzelwamburu** [comment]
am using the i2c code example

**Comment by theopensourcerer** [comment]
I've not used Energia but I do use this in PlatformIO and it works fine. 

Have you tried it in an another IDE? 

What platform (MCU) are you building for?

**Comment by finitespace** [comment]
denzelwamburu,

NaN (not a number) is a C++ 11 construct.  Do you have the capability in Energia to specify using the c++ 11 compiler? If not you may need to define NAN in the BME280 file as well as the function isnan();

Tyler

**Comment by finitespace** [comment]
You can put something along the lines of:

#define NAN        1e+30  /* _HUGE_ENUF*/
#define isnan(n) n == float(NaN)

in the top of your BME280.cpp file.

Tyler

**Comment by denzelwamburu** [comment]
Hi @finitespace , let me look at it tomorrow and give you the feedback. Thanks.

**Comment by denzelwamburu** [comment]
@theopensourcerer MSP430

**Comment by denzelwamburu** [comment]
@finitespace  Where exactly should this be placed?

**Comment by finitespace** [comment]
At the top of the BME280.cpp file should work.

Tyler
