### ISSUE TITLE
Do mMultiple Sensors

### ISSUE THREAD

**Issue by Eheran1** [finitespace/BME280#30]
Do multiple sensors get their own calibration values?
Or do they all use the same set?

PS: Why cant I edit the title.... urgh... sorry.

**Comment by finitespace** [comment]
Eheran1,

Yes, they should get their own cal values when the DIGs get read off the device.

Tyler

**Comment by Eheran1** [comment]
Ah, thank you. Thats great!
I think that makes this (one of) the best librarys. The other one I know about that supports them with their own calibration only works on I2C = max 2 sensors. (cactus.io)
