### ISSUE TITLE
ARDUINO_ARCH_ESP8266 issue

### ISSUE THREAD

**Issue by Fbo06** [finitespace/BME280#34]
Hello, can you please tell me why i cannot compile this code 
...
#define ARDUINO_ARCH_ESP8266
#include <BME280I2C.h>
...
compile error:
: undefined reference to `BME280I2C::begin()'
: In function `setup()':
: undefined reference to `BME280I2C::begin()'
: ld returned 1 exit status

if i comment the line #define ARDUINO_ARCH_ESP8266
everything it's compile OK

any advise please

**Comment by coelner** [comment]
try to patch the file BME280I2C.h in line 63 and move the ''#endif'' a line up.

**Comment by Fbo06** [comment]
Thank you sooooo much coelner
