### ISSUE TITLE
Altitude calculation formula

### ISSUE THREAD

**Issue by jirkaptr** [finitespace/BME280#44]
The used formula is very simple, but very inaccurate, usable for rough calculation. Much better results are provided by two variants of the calculation in http://drkfs.net/correctiontosealevel.htm.   The Laplace’s formula is very versatile, while the Babinet’s formula is a good compromise of precision and simplicity.
The auxiliary value e/b can be derived e.g. in http://www.weather.gov/media/epz/wxcalc/vaporPressure.pdf.

**Comment by finitespace** [comment]
Great idea! Sounds like some fun algorithmic development.

**Comment by finitespace** [comment]
#54
