### ISSUE TITLE
How to get altitude?

### ISSUE THREAD

**Issue by pro100svitlo** [finitespace/BME280#97]
Hi!
I am newone in arduino stuff and I stuck with altitude.
I got how I can get pres, temp, hum.... but how to get altitude?
There is no such method in bme and no example on READ file...

Thanks for understanding :)

**Comment by coelner** [comment]
Hey, look at the example:
https://github.com/finitespace/BME280/blob/master/examples/Environment_Calculations/Environment_Calculations.ino

It should answer your question. Please close the issue if it solves your question.

**Comment by pro100svitlo** [comment]
thanks!
and sorry for disturb :)
